version: "3.8"
services:

  web:
   image: nginx:test
   container_name: nginx
   volumes:
    - ./nginx/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./www/web:/usr/share/nginx/html
   ports:
    - 8080:80
   links:
    - php
   networks:
    efk-network:
   logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.16.0.30:24224
        tag: nginx

  php:
    image: php:test
    container_name: php
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www/web:/usr/share/nginx/html
    links:
      - redis-master
    networks:
      efk-network:  
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.16.0.30:24224
        tag: php

  redis-master:
    image: redis:test
    container_name: redis-master
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/redis-master/redis.conf:/etc/redis/redis.conf
    networks:
      efk-network:
        ipv4_address: 192.16.0.6
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.16.0.30:24224
        tag: redis-master

  redis-slave1:
    image: redis:test
    container_name: redis-slave1
    ports:
      - 6380:6379
    volumes:
      - ./data/redis/redis-slave1/redis.conf:/etc/redis/redis.conf
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    networks:
      efk-network:
        ipv4_address: 192.16.0.7
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.16.0.30:24224
        tag: redis-slave1

  redis-slave2:
    image: redis:test
    container_name: redis-slave2
    ports:
      - 6381:6379
    volumes:
      - ./data/redis/redis-slave2/redis.conf:/etc/redis/redis.conf
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
      - redis-slave1
    networks:
      efk-network:
        ipv4_address: 192.16.0.8
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.16.0.30:24224
        tag: redis-slave2

networks:  
  efk-network:
    external:
     name: efk-network