version: "3.8"
services:

  web:
   image: nginx:test
   container_name: nginx
   volumes:
    - ./nginx/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./www/web:/usr/share/nginx/html
   ports:
    - 8080:80
   links:
    - php
   networks:
    My_networkforall:

  php:
    image: php:test
    container_name: php
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www/web:/usr/share/nginx/html
    links:
      - redis-master
    networks:
      My_networkforall:  

  redis-master:
    image: redis:test
    container_name: redis-master
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/redis-master/redis.conf:/etc/redis/redis.conf
    networks:
      My_networkforall:
        ipv4_address: 192.16.0.6

  redis-slave1:
    image: redis:test
    container_name: redis-slave1
    ports:
      - 6380:6380
    volumes:
      - ./data/redis/redis-slave1/redis.conf:/etc/redis/redis.conf
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    networks:
      My_networkforall:
        ipv4_address: 192.16.0.7

  redis-slave2:
    image: redis:test
    container_name: redis-slave2
    ports:
      - 6381:6381
    volumes:
      - ./data/redis/redis-slave2/redis.conf:/etc/redis/redis.conf
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
      - redis-slave1
    networks:
      My_networkforall:
        ipv4_address: 192.16.0.8

networks: 
#建立一個給所有container使用的網路 
  My_networkforall:
    driver: bridge
    name: My_network
    ipam:
      config:
       - subnet: 192.16.0.0/16
         gateway: 192.16.0.1