version: "3.9"
services:
  db:
    image: mysql:8.2.0
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wpdb
      MYSQL_USER: consle
      MYSQL_PASSWORD: x941u/3jo6
    volumes:
    - ./db-data:/var/lib/mysql
  adminer:
    image: adminer:4.8.1
    ports:
    - 8080:8080
    depends_on:
    - db
  wordpress:
    image: wordpress:6.4.2
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: consle
      WORDPRESS_DB_PASSWORD: x941u/3jo6
      WORDPRESS_DB_NAME: wpdb
    volumes:
    - ./wp-data:/var/www/html
    depends_on:
    - db
